HCI/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^Vote/', include('Vote.urls')),
]

Vote/urls.py
from django.conf.urls import url
from . import views

app_name = 'Vote'
urlpatterns = [
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^vote/', views.vote, name='vote'),
    url(r'^results/', views.results, name='results'),
    url(r'^home/', views.home, name='home'),
    url(r'^home_hindi/', views.home_hindi, name='home_hindi'),
    url(r'^home_german/', views.home_german, name='home_german'),
    url(r'^home_spanish/', views.home_spanish, name='home_spanish'),
    url(r'^about/', views.about, name='about'),
    url(r'^voted/', views.voted, name='voted'),
]

Vote/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    voted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Position(models.Model):
    position = models.CharField(max_length=50)
    no_of_candidates = models.IntegerField(default=0)

    def __str__(self):
        return self.position


class Candidate(models.Model):
    candidate = models.ForeignKey(Position, on_delete=models.CASCADE)

    name = models.CharField(max_length=50)
    Description = models.TextField()
    image = models.ImageField(upload_to='Vote/static/Vote', blank=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

Vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import User, UserProfile, Position, Candidate
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
import numpy as np
from io import BytesIO
import base64


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/Vote/home/')
            else:
                return HttpResponseRedirect("Account disabled")
        else:
            print("Invalid credentials: {0}, {1}".format(username, password))
            return HttpResponseRedirect("Invalid login credentials")
    else:
        return render(request, 'Vote/login.html', {})


@login_required(redirect_field_name='/Vote/login/')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/Vote/home/')


def home(request):
    context = {}
    return render(request, 'Vote/home.html', context)


def home_hindi(request):
    context = {}
    return render(request, 'Vote/home_hindi.html', context)


def home_german(request):
    context = {}
    return render(request, 'Vote/home_german.html', context)


def home_spanish(request):
    context = {}
    return render(request, 'Vote/home_spanish.html', context)


def vote(request):
    context = {}
    try:
        pos = Position.objects.all()
        user = User.objects.get(username=request.user.username)
        profile = UserProfile.objects.get(user=user)
        context['candidates'] = []
        if profile.voted:
            return HttpResponseRedirect('/Vote/voted/')
        else:
            for c in pos:
                can = []
                candidate = Candidate.objects.filter(candidate=c)
                for i in range(0, c.no_of_candidates):
                    can.append([candidate[i], c.position])
                context['candidates'].append(can)
    except:
        return HttpResponseRedirect("/Vote/login/")
    if request.method == 'POST':
        pos = Position.objects.all()
        for c in pos:
            s = 'candidate' + c.position
            selected_candidate = Candidate.objects.get(pk=request.POST[s])
            selected_candidate.votes += 1
            selected_candidate.save()
            profile.voted = True
            profile.save()
        else:
            print("No Post")

    return render(request, 'Vote/vote.html', context)


def results(request):
    context = {}
    pos = Position.objects.all()
    context['candidates'] = []
    for c in pos:
        fig = plt.figure()
        vot = []   # No of votes for graph
        can = []
        cand = []  # Name of the candidates for graph labelling
        candidate = Candidate.objects.filter(candidate=c)
        for i in range(0, c.no_of_candidates):
            can.append([candidate[i]])
            cand.append(candidate[i].name)
            vot.append(candidate[i].votes)
            
        plt.pie(vot, labels=cand, autopct='%1.1f%%', shadow=True, startangle=140)
        plt.axis('equal')
        name = "/Users/apoorvagarwal/E-vote/Vote/static/Vote/" + c.position + '.png'
        fig.savefig(name)
        can[0].append(c)
        can[0].append(name)
        plt.close(fig)
        context['candidates'].append(can)

    return render(request, 'Vote/results.html', context)


def about(request):
    context = {}
    return render(request, 'Vote/about.html', context)


def voted(request):
    context = {}
    return render(request, 'Vote/voted.html', context)

Vote/templates/Vote/about.html
!doctype html>
<html>
{% load static %}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, iniital-scale=1;">
<title>Chunaav</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<link rel="stylesheet" type="text/css" href="{% static 'Vote/credits.css' %}">
<link rel="shortcut icon" type="image/x-icon" href="logo.jpg" />
<style>

.navbar-brand{
  float: none;

}
</style>
</head>
<body>
   <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container-fluid">
       <div class=" navbar-header">
	   <img src="{% static 'Vote/logo.jpg' %}" width=50 height=50 class = 'logoq'>
           <a class="navbar-brand" href="#"><b>Chunaav</b></a>

	   </div>
      <ul class="nav navbar-nav">
       <li ><a href="{% url 'Vote:home' %}">Home</a></li>
       <li><a href="{% url 'Vote:vote' %}">Vote</a></li>
       <li><a href="{% url 'Vote:results' %}">Results</a> </li>
	   <li class="active"><a href ="{% url 'Vote:about' %}">About</a></li>
	   <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">English
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Spanish</a></li>
          <li><a href="{% url 'Vote:home_german' %}">German</a></li>
          <li><a href="{% url 'Vote:home_hindi' %}">Hindi</a></li>
          <li><a href="#">Dutch</a></li>
          <li><a href="#">Portugese</a></li>
          <li><a href="#">Madrain</a></li>
        </ul>
      </li>
       </ul>

      {% if user.is_authenticated %}
       <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'Vote:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
       </ul>
      {% else %}
       <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'Vote:login' %}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
       </ul>
      {% endif %}
     </div>
    </nav>

	<div class="page-header bg-2">
        <br><br>
     <h1 align="center" ><strong>Chunaav:the most popular voting website for creating polls &</strong> </h1>
	 <h1 align="center"><strong>coordinating meetings</strong></h1>
   </div>


   <!----row column---->
   <div class="row bg-10">
       <div class="col-lg-1"></div>
     <div class="col-lg-4" class="slideanim" class="well"><img src="{% static 'Vote/logo.jpg' %}" class="img-thumbnail" ></div>
	 <br><br><br>
       <div class="col-lg-6"><h3 align="center"><strong>Website Designed By The Chunaav Team. Dedicated towards enabling fair elections.</strong></h3>
           <h4><br><br><strong>*  Mayank Jindal</strong></h4>
           <h4><br><strong>*  Apoorv Agarwal</strong></h4>
           <h4><br><strong>*  Abhinav Chopra</strong></h4>
           <h4><br><strong>*  Divyanshu Gupta</strong></h4>
           <h4><br><strong>*  Akshay Garg</strong></h4>
	 </div>
	 </div>

</body>
</html>
	

Vote/templates/Vote/home_german.html
<!doctype html>
<html>
<head>
    {% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, iniital-scale=1;">
<title>Chunaav</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Vote/home.css' %}">
<style>
footer .glyphicon {
    font-size: 20px;
    margin-bottom: 20px;
    color: #f4511e;
}
.navbar-brand{
  float: none;
}
</style>
</head>
<body>
   <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container-fluid">
       <div class=" navbar-header">
          <img src="{% static 'Vote/logo.jpg' %}" alt="some text" width=50 height=50 class = "logoq">
        <a class="navbar-brand" href="#"><b>Chunaav</b></a>

       </div>
      <ul class="nav navbar-nav">
       <li class="active"><a href="#">Home</a></li>
       <li><a href="{% url 'Vote:vote' %}">Vote</a></li>
       <li><a href="{% url 'Vote:results' %}">Results</a> </li>
	   <li><a href ="{% url 'Vote:about' %}">About</a></li>
	   <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">German
        <span class="caret"></span></a>
        <ul class="dropdown-menu">

          <li><a href="{% url 'Vote:home_spanish' %}">Spanish</a></li>
          <li><a href="{% url 'Vote:home_hindi' %}">Hindi</a></li>
          <li><a href="{% url 'Vote:home' %}">English</a></l
          <li><a href="#">Dutch</a></li>
          <li><a href="#">Portugese</a></li>
          <li><a href="#">Madrain</a></li>
        </ul>
      </li>
       </ul>

        {% if user.is_authenticated %}
       <ul class="nav navbar-nav navbar-right">
       <li><a href="{% url 'Vote:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
       </ul>
         {% else %}
         <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'Vote:login' %}"><span class="glyphicon glyphicon-log-in"></span> Anmeldung</a></li>
        </ul>
         {% endif %}
     </div>
    </nav>
   <div class="page-header bg-6">

     <h1 align="center" ><strong>Chunaav:die beliebteste Voting-Website zum Erstellen von Umfragen </h1>
       <h1 align="center">Koordination von Meetings</strong></h1>
   </div>
   <!----row column---->
   <div class="row">
     <div class="col-lg-4" class="slideanim"><img src="{% static 'Vote/voting.jpeg' %}" class="img-thumbnail" ></div>
	 <div class="col-lg-8"><h4>Die Online-Voting-Website Chunaav wurde 2007 in der Schweiz gegründet und wurde bereits zwei Jahre später in der Kategorie Web Services & Applications der 13. Annual Webby Awards zu einem der Besten gewählt.Zudem erfreut Doodle Millionen von Nutzern seit geraumer Zeit: Die Voting-Website hat im Oktober 2011 die Marke von 10 Millionen Nutzern überschritten und im Januar 2013 die Marke von 15 Millionen Nutzern überschritten. Die bloße Popularität dieser Voting-Website beweist, dass sie eine <strong>Toller Service, der einfach zu bedienen ist</strong> and at the right price – free! – which ensures that happy users keep returning.
     </h4></div>
	</div>
    <div class="row bg-5" >
     <div class="col-lg-8" class="slideanim"><h2> Was macht diese Website so besonders?</h2>
      <h4>Chunaav beschränkt nicht die Anzahl der Umfragen, die Sie erstellen können. Im Gegensatz zu den meisten Voting-Websites können Sie den kostenlosen Dienst so oft nutzen, wie Sie möchten. Es ist eine schnelle und einfache Möglichkeit, RSVPs für eine Party zu organisieren oder Ihre Kollegen darüber abstimmen zu lassen, wo die nächste Party stattfinden soll.
         </br></br>Chunaav hat ein sehr minimalistisches, benutzerfreundliches Design. Wenn Sie sich für einen Premium-Account anmelden, können Sie die Voting-Website-Vorlage leicht ändern, aber der grundlegende Informationsfluss und das Layout der Online-Voting-Abstimmung bleiben unverändert. </br></br>Es gibt keinen Aufwand, keine Aufregung und keine langwierigen Schritte, die Sie auffordern, Informationen auszufüllen. In der Tat müssen Sie sich nicht einmal für ein Konto anmelden (das auch kostenlos ist). Diese Abstimmungswebsite benötigt keine Handynummer, speichert Ihre E-Mail-Adresse nicht für den Versand von Newslettern und verkauft Ihre Kontaktinformationen niemals an Drittanbieter.
	   </h4></div>
	    <div class="col-lg-4"><br><br><img src="{% static 'Vote/e_vote.jpg' %}" class="img-thumbnail" ></div>
	  </div>
	  </div>
	  <div class="row">
		<div class="col-lg-12" align="center"><h2>Wählen Sie nur einen Klick entfernt</h2>
		<h4 align="center">Doodle bietet zusätzliche Funktionen wie den kostenlosen MeetMe-Service, der ein Kontaktcenter für die Koordination von Besprechungen ist. Es gibt auch eine mobile Anwendung, so dass Sie, wenn Sie unterwegs sind, nicht die Voting-Website in Ihrem Browser aufrufen müssen, sondern einfach die App öffnen und Ihre Stimme abgeben oder einen Termin innerhalb von Sekunden planen. Es ist so einfach zu bedienen und kostet nichts: also warum nicht Doodle einen Versuch für Ihre nächste Umfrage oder Fragebogen?
		</h4><br>
        <a href="{% url 'Vote:vote' %}"><button type="button" class="btn1">Abstimmung erstellen</button><br><br></a>
		</div>
	   </div>

		 <br>
		 <br>


<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
	<div class="container-fluid bg-4">
  <h2 class="text-center">CONTACT</h2>
  <div class="row row2">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> BML Munjal Univeristy</p>
      <p><span class="glyphicon glyphicon-phone"></span> +91 9953918594</p>
      <p><span class="glyphicon glyphicon-envelope"></span> abhinavchopra22@gmail.com</p>
    </div>
    <div class="col-sm-7">
      <div class="row row2">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row row2">
        <div class="col-sm-12 form-group" align = "center">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>

<footer class="container-fluid  bg-4 text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>MADE WITH SKILL! NOT LOVE.</a></p>
</footer>

</div>
</body>
</html>

Vote/templates/Vote/home_spanish.html
<!doctype html>
<html>
<head>
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, iniital-scale=1;">
<title>Chunaav</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Vote/home.css' %}">
<style>
footer .glyphicon {
    font-size: 20px;
    margin-bottom: 20px;
    color: #f4511e;
}
</style>
</head>
<body>
   <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container-fluid">
       <div class=" navbar-header">
         <a class="navbar-brand" href="#">Chunaav</a>
           <img src="{% static 'Vote/logo.jpg' %}" alt="some text" width=50 height=50>
       </div>
      <ul class="nav navbar-nav">
       <li class="active"><a href="#">Casa</a></li>
       <li><a href="{% url 'Vote:vote' %}">Votar</a></li>
       <li><a href="{% url 'Vote:results' %}">Ayuda</a> </li>
	   <li><a href ="{% url 'Vote:about' %}">Enviar</a></li>
	   <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Spanish
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'Vote:home_german' %}">German</a></li>
          <li><a href="{% url 'Vote:home_hindi' %}">Hindi</a></li>
          <li><a href="{% url 'Vote:home' %}">English</a></li>

        </ul>
      </li>
       </ul>

        {% if user.is_authenticated %}
       <ul class="nav navbar-nav navbar-right">
       <li><a href="{% url 'Vote:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
       </ul>
         {% else %}
         <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'Vote:login' %}"><span class="glyphicon glyphicon-log-in"></span>Iniciar sesión</a></li>
        </ul>
         {% endif %}
     </div>
    </nav>
   <div class="page-header bg-6">
     <h1 align="center" >Chunaav:Doodle: el sitio web de votación más popular para crear encuestas y</h1>
	 <h1 align="center">reuniones de coordinación</h1>
   </div>
   <!----row column---->
   <div class="row">
     <div class="col-lg-4" class="slideanim"><img src="{% static 'Vote/voting.jpeg' %}" class="img-thumbnail" ></div>
	 <div class="col-lg-8"><h4>El sitio web de votación en línea Doodle se fundó en Suiza en 2007 y solo dos años más tarde fue nombrado uno de los mejores en la categoría Servicios web y aplicaciones de la 13ª entrega anual de Webby Awards. Además, Doodle ha complacido a millones de usuarios durante bastante tiempo: el sitio web de votación superó los 10 millones de usuarios en octubre de 2011 y superó los 15 millones de usuarios en enero de 2013. La gran popularidad de este sitio web de votación demuestra que ofrece una <strong>gran servicio que es fácil de usar</strong> y al precio correcto - ¡gratis! - que asegura que los usuarios felices sigan regresando.
     </h4></div>
	</div>
    <div class="row bg-5" >
     <div class="col-lg-8" class="slideanim"><h2> ¿Qué hace que este sitio web sea tan especial?</h2>
      <h4>Chunaav no limita el número de encuestas que puedes crear. A diferencia de la gran mayoría de los sitios web de votación, puede continuar utilizando el servicio gratuito con la frecuencia que desee. Es una forma rápida y fácil de organizar las confirmaciones de asistencia para una fiesta o dejar que sus colegas emitan su voto sobre dónde se realizará la próxima fiesta de trabajo.
         </br></br>Chunaav tiene un diseño muy minimalista y fácil de usar. Si se registra para obtener una cuenta premium, puede modificar ligeramente la plantilla del sitio web de votación, pero el flujo básico de agregar información y el diseño de la boleta de votación en línea sigue siendo el mismo.<br><br>No hay problemas, ni problemas, ni largos pasos que le piden que complete la información. De hecho, ni siquiera tiene que registrarse para obtener una cuenta (que también es gratis). ¡Este sitio web de votación no necesita su número de teléfono móvil, no guarda su dirección de correo electrónico para enviar boletines informativos y nunca venderá su información de contacto a terceros anunciantes!
	   </h4></div>
	    <div class="col-lg-4"><img src="{% static 'Vote/e_vote.jpg' %}" class="img-thumbnail" ></div>
	  </div>
	  </div>
	  <div class="row">
		<div class="col-lg-12" align="center"><h2>Votar a un clic de distancia</h2>
		<h4 align="center">Chunaav tiene características adicionales, como el servicio gratuito MeetMe, que es un centro de contacto para coordinar reuniones. También hay una aplicación móvil, de modo que si está en movimiento, no tiene que abrir el sitio web de votación en su navegador, sino simplemente abrir la aplicación y emitir su voto o programar una cita en cuestión de segundos. Es tan fácil de usar y no cuesta nada: ¿por qué no probar Doodle para su próxima encuesta o cuestionario?
		</h4><br>
        <a href="{% url 'Vote:vote' %}"><button type="button" class="btn btn-basic">Abstimmung erstellen</button><br><br></a>
		</div>
	   </div>

		 <br>
		 <br>


<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
	<div class="container-fluid bg-4">
  <h2 class="text-center">CONTACT</h2>
  <div class="row row2">
    <div class="col-sm-5">
      <p>Póngase en contacto con nosotros y nos pondremos en contacto con usted dentro de las 24 horas.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> BML Munjal Univeristy</p>
      <p><span class="glyphicon glyphicon-phone"></span> +91 9953918594</p>
      <p><span class="glyphicon glyphicon-envelope"></span> abhinavchopra22@gmail.com</p>
    </div>
    <div class="col-sm-7">
      <div class="row row2">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row row2">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>

<footer class="container-fluid  bg-4 text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>MADE WITH SKILL! NOT LOVE.</a></p>
</footer>

</div>
</body>
</html>

Vote/templates/Vote/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, iniital-scale=1;">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Vote/login.css' %}">
<style>
footer .glyphicon {
    font-size: 20px;
    margin-bottom: 20px;
    color: #f4511e;
}
.navbar-brand{
  float: none;

}
</style>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
     <div class="container-fluid">
       <div class=" navbar-header">
         <img src="{% static 'Vote/logo.jpg' %}" alt="some text" width=50 height=50 class = 'logoq'>
           <a class="navbar-brand" href="#"><b>Chunaav</b></a>

       </div>
      <ul class="nav navbar-nav">
       <li class="active"><a href="{% url 'Vote:home' %}">Home</a></li>
       <li><a href="{% url 'Vote:vote' %}">Vote</a></li>
       <li><a href="{% url 'Vote:results' %}">Results</a> </li>
	   <li><a href ="{% url 'Vote:about' %}">About</a></li>
	   <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">English
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Spanish</a></li>
          <li><a href="#">German</a></li>
          <li><a href="Vote:home_hindi">Hindi</a></li>
          <li><a href="#">Dutch</a></li>
          <li><a href="#">Portugese</a></li>
          <li><a href="#">Madrain</a></li>
        </ul>
      </li>
       </ul>

        {% if user.is_authenticated %}
       <ul class="nav navbar-nav navbar-right">
       <li><a href="{% url 'Vote:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
       </ul>
         {% else %}
         <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'Vote:login' %}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
        </ul>
         {% endif %}
     </div>
    </nav>
<div class="row">
<div class="col-lg-12">
<div class="form_l1" align="center">LOGIN FORM</div>
<div class="form_div" align="center">
<p class="form_label1">Enter the username and password to log in:</p>
<form method="post" action="Vote/login/">{% csrf_token %}

    <input type="text" name="username" placeholder="   Enter Username" value=""/>
    <br><br>
    <input type="password" name="password" placeholder="   Enter Password" value=""/>
    <br><br>
    <a href="{% url 'Vote:vote' %}"><input type="submit" name="submit" /></a>

</form>
</div>
</div>
</div>
<div id="backgroundImage">
 <div class="main">
 </div>
</div>


</div>
</body>
</html>